simulate failure scenario

diff --git a/.github/workflows/if-example-specialfunctions.yml b/.github/workflows/if-example-specialfunctions.yml
--- a/.github/workflows/if-example-specialfunctions.yml
+++ b/.github/workflows/if-example-specialfunctions.yml
@@ -11,7 +11,9 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - name: static code analysis
-              run: echo "feature branch static code analysis"
+              run: |
+                echo "feature branch static code analysis"
+                exit 1 # simulate failure for demonstration
     develop:
         if: github.ref_name == 'develop' && github.event_name == 'push'
         runs-on: ubuntu-latest
@@ -31,7 +33,8 @@ jobs:
         steps:
           - name: notify success
             run: echo "workflow succeeded"
-    failure: 
+    failure:
+        needs: [feature, develop, deploy]
         if: failure()
         runs-on: ubuntu-latest
         steps:
